# run [docker compose up/docker compose down] run docker compose
version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=nZNnn41RuhrDEZcjO01X
      - POSTGRES_DB=transfer_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: 
      - DB_SOURCE=postgresql://root:nZNnn41RuhrDEZcjO01X@transfer-bank.ca8is6ljjqfm.ap-southeast-1.rds.amazonaws.com:5432/transfer_bank
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]