apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-bank-api-deployment
  labels:
    app: transfer-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transfer-bank-api
  template:
    metadata:
      labels:
        app: transfer-bank-api
    spec:
      containers:
      - name: transfer-bank-api
        image: 502320843173.dkr.ecr.ap-southeast-1.amazonaws.com/banktransfer:ce552342b29e2f32769b0dd1fc44d69b1d044471
        imagePullPolicy: Always
        ports:
        - containerPort: 8080