apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-bank-api-deployment
  labels:
    app: transfer-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transfer-bank-api
  template:
    metadata:
      labels:
        app: transfer-bank-api
    spec:
      containers:
      - name: transfer-bank-api
        image: 502320843173.dkr.ecr.ap-southeast-1.amazonaws.com/banktransfer:da5a3854e40e9d07f7bb241957c002e812daae81
        imagePullPolicy: Always
        ports:
        - containerPort: 8080